"use client";

import React, { useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Wand2, Rocket, Share2, Download, ArrowRight } from "lucide-react";
import { toast, Toaster } from "sonner";
import html2canvas from "html2canvas";

// --- Types & Data ---

interface LeanCanvasData {
  problem: string;
  customerSegments: string;
  uniqueValueProposition: string;
  solution: string;
  channels: string;
  revenueStreams: string;
  costStructure: string;
  keyMetrics: string;
  unfairAdvantage: string;
}

const initialData: LeanCanvasData = {
  problem: "",
  customerSegments: "",
  uniqueValueProposition: "",
  solution: "",
  channels: "",
  revenueStreams: "",
  costStructure: "",
  keyMetrics: "",
  unfairAdvantage: "",
};

// --- Page Component ---

export default function LeanCanvasPage() {
  const router = useRouter();
  const [topic, setTopic] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [canvasData, setCanvasData] = useState<LeanCanvasData>(initialData);
  const canvasRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast.error("아이디어를 입력해주세요!");
      return;
    }

    setIsLoading(true);
    // TODO: AI API Integration
    setTimeout(() => {
      setCanvasData({
        problem: `1. 시장의 기존 솔루션이 너무 복잡함\n2. 높은 가격대로 인한 접근성 저하\n3. ${topic} 관련 전문 지식 부족`,
        customerSegments: `1. ${topic}에 관심 있는 2030 세대\n2. 효율성을 추구하는 실무자\n3. 새로운 도구를 찾는 얼리어답터`,
        uniqueValueProposition: `"${topic}"을(를) 위한\n가장 쉽고 직관적인 솔루션.\n복잡함은 줄이고, 핵심 가치에 집중.`,
        solution: `1. AI 기반 자동화 시스템\n2. 원클릭 워크플로우\n3. 사용자 친화적인 UX/UI`,
        channels: `1. Instagram & TikTok 숏폼 마케팅\n2. 관련 네이버 카페 및 커뮤니티\n3. 인플루언서 제휴`,
        revenueStreams: `1. 부분 유료화 (Freemium)\n2. 프리미엄 구독 멤버십\n3. 기업용 라이선스 판매`,
        costStructure: `1. 클라우드 서버 운영비\n2. 마케팅 및 광고 집행비\n3. 초기 개발 인건비`,
        keyMetrics: `1. 월간 활성 사용자 (MAU)\n2. 고객 획득 비용 (CAC)\n3. 유료 전환율 (Conversion Rate)`,
        unfairAdvantage: `1. 자체 개발 데이터셋\n2. 압도적인 사용자 경험\n3. 강력한 초기 팬덤`,
      });
      setIsLoading(false);
      setIsGenerated(true);
      toast.success("린 캔버스가 생성되었습니다!");
    }, 2000);
  };

  const handleChange = (key: keyof LeanCanvasData, value: string) => {
    setCanvasData((prev) => ({ ...prev, [key]: value }));
  };

  const handleDownloadImage = async () => {
    if (!canvasRef.current) return;
    try {
      const canvas = await html2canvas(canvasRef.current, { scale: 2 });
      const link = document.createElement("a");
      link.download = `${topic || "leancanvas"}-vibefolio.png`;
      link.href = canvas.toDataURL();
      link.click();
      toast.success("이미지로 저장되었습니다.");
    } catch (e) {
      console.error(e);
      toast.error("저장에 실패했습니다.");
    }
  };

  const handleStartProject = () => {
    // Format to Markdown
    const content = `
## 🚀 ${topic ? topic + ' - ' : ''}린 캔버스 기획안

> **Generated by Vibefolio AI Planner**

### 1. 문제 (Problem)
${canvasData.problem}

### 2. 고객군 (Customer Segments)
${canvasData.customerSegments}

### 3. 고유 가치 제안 (Unique Value Proposition)
${canvasData.uniqueValueProposition}

### 4. 솔루션 (Solution)
${canvasData.solution}

### 5. 경쟁 우위 (Unfair Advantage)
${canvasData.unfairAdvantage}

### 6. 채널 (Channels)
${canvasData.channels}

### 7. 핵심 지표 (Key Metrics)
${canvasData.keyMetrics}

### 8. 비용 구조 (Cost Structure)
${canvasData.costStructure}

### 9. 수익원 (Revenue Streams)
${canvasData.revenueStreams}
    `.trim();

    // Save to LocalStorage for import
    localStorage.setItem('project_import_content', content);
    localStorage.setItem('project_import_title', topic);
    localStorage.setItem('project_import_type', 'lean_canvas');
    
    // Redirect
    toast.success("프로젝트 에디터로 이동합니다...");
    setTimeout(() => {
        router.push('/project/upload');
    }, 1000);
  };

  return (
    <div className="min-h-screen bg-white">
      <Toaster position="top-center" richColors />
      
      {/* Hero Section */}
      <div className="bg-[#111] text-white py-20 px-4 relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-full opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]"></div>
        <div className="absolute -top-20 -right-20 w-96 h-96 bg-purple-600 rounded-full blur-[100px] opacity-40"></div>
        <div className="absolute -bottom-20 -left-20 w-96 h-96 bg-green-500 rounded-full blur-[100px] opacity-30"></div>

        <div className="max-w-4xl mx-auto text-center relative z-10 animate-in fade-in slide-in-from-bottom-6 duration-700">
          <div className="inline-block px-3 py-1 bg-white/10 rounded-full text-xs font-bold text-green-400 mb-6 border border-white/10 backdrop-blur-sm">
            ✨ LABS : AI 기획 도우미
          </div>
          <h1 className="text-4xl md:text-6xl font-black mb-6 leading-tight tracking-tight">
            막연한 아이디어, <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">10초 만에 기획서</span>로 만드세요.
          </h1>
          <p className="text-lg text-gray-400 mb-10 max-w-2xl mx-auto leading-relaxed">
            스타트업의 필수품 '린 캔버스(Lean Canvas)'를 AI가 대신 작성해드립니다.<br className="hidden md:block"/>
            작성된 기획안으로 바로 포트폴리오 프로젝트를 시작해보세요.
          </p>

          <div className="max-w-xl mx-auto relative group">
            <div className="absolute inset-0 bg-gradient-to-r from-green-500 to-purple-600 rounded-2xl blur opacity-30 group-hover:opacity-50 transition-opacity"></div>
            <div className="relative bg-white rounded-2xl p-2 flex items-center shadow-2xl">
              <Input
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                placeholder="예: 20대 대학생을 위한 AI 자소설 첨삭 서비스"
                className="border-0 h-14 text-lg text-black placeholder:text-gray-400 focus-visible:ring-0 bg-transparent px-4"
              />
              <Button 
                onClick={handleGenerate} 
                disabled={isLoading}
                className="h-12 px-8 bg-black hover:bg-gray-800 text-white rounded-xl font-bold text-lg gap-2 transition-all"
              >
                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Wand2 className="w-5 h-5" />}
                {isLoading ? "생성 중..." : "AI 생성"}
              </Button>
            </div>
          </div>
          <p className="text-xs text-gray-500 mt-4">비로그인 상태에서도 무료로 이용할 수 있습니다.</p>
        </div>
      </div>

      {/* Canvas Section */}
      <div className="container mx-auto px-4 py-16">
        <div className={`transition-all duration-1000 ${isGenerated ? 'opacity-100 translate-y-0' : 'opacity-40 translate-y-10 brightness-95 grayscale'}`}>
            
            {/* Toolbar */}
            <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-bold flex items-center gap-2">
                    📊 린 캔버스 결과
                    {!isGenerated && <span className="text-sm font-normal text-gray-400 ml-2">(생성 대기 중...)</span>}
                </h2>
                <div className="flex gap-3">
                    <Button variant="outline" onClick={handleDownloadImage} disabled={!isGenerated} className="gap-2">
                        <Download className="w-4 h-4" /> 이미지 저장
                    </Button>
                    <Button onClick={handleStartProject} disabled={!isGenerated} className="bg-green-600 hover:bg-green-700 text-white gap-2 font-bold shadow-lg hover:translate-y-[-2px] transition-all">
                        <Rocket className="w-4 h-4" /> 이 기획으로 프로젝트 시작하기
                    </Button>
                </div>
            </div>

            {/* Grid */}
            <div ref={canvasRef} className="bg-white p-8 rounded-2xl shadow-xl border border-gray-100">
                {/* Canvas Header (For Screenshot) */}
                <div className="mb-8 border-b border-gray-100 pb-4 flex justify-between items-end">
                    <div>
                        <h3 className="text-3xl font-black text-gray-900">{topic || "나의 아이디어"}</h3>
                        <p className="text-sm text-gray-500 mt-1">Generated by Vibefolio AI</p>
                    </div>
                    <div className="text-right">
                        <div className="text-xs text-gray-400">Date</div>
                        <div className="font-medium">{new Date().toLocaleDateString()}</div>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-5 md:grid-rows-3 gap-4 min-h-[800px]">
                    {/* 1. Problem */}
                    <CanvasBlock
                    title="1. 문제 (Problem)"
                    subtitle="고객이 겪는 상위 3가지 문제"
                    value={canvasData.problem}
                    onChange={(v) => handleChange("problem", v)}
                    className="md:row-span-2 md:col-span-1"
                    icon="🔥"
                    />
                    
                    {/* 4. Solution */}
                    <CanvasBlock
                    title="4. 솔루션 (Solution)"
                    subtitle="각 문제에 대한 해결책"
                    value={canvasData.solution}
                    onChange={(v) => handleChange("solution", v)}
                    className="md:col-span-1"
                    icon="💡"
                    />

                    {/* 3. UVP */}
                    <CanvasBlock
                    title="3. 가치 제안 (UVP)"
                    subtitle="차별화된 핵심 가치 메시지"
                    value={canvasData.uniqueValueProposition}
                    onChange={(v) => handleChange("uniqueValueProposition", v)}
                    className="md:row-span-2 md:col-span-1 bg-purple-50/50 border-purple-100"
                    icon="💎"
                    isHighlight
                    />

                    {/* 9. Unfair Advantage */}
                    <CanvasBlock
                    title="9. 경쟁 우위 (Advantage)"
                    subtitle="쉽게 복제할 수 없는 강점"
                    value={canvasData.unfairAdvantage}
                    onChange={(v) => handleChange("unfairAdvantage", v)}
                    className="md:col-span-1"
                    icon="🛡️"
                    />

                    {/* 2. Customer Segments */}
                    <CanvasBlock
                    title="2. 고객군 (Segments)"
                    subtitle="목표 고객 및 얼리어답터"
                    value={canvasData.customerSegments}
                    onChange={(v) => handleChange("customerSegments", v)}
                    className="md:row-span-2 md:col-span-1"
                    icon="🎯"
                    />

                    {/* 8. Key Metrics */}
                    <CanvasBlock
                    title="8. 핵심 지표 (Metrics)"
                    subtitle="성공을 측정하는 핵심 숫자"
                    value={canvasData.keyMetrics}
                    onChange={(v) => handleChange("keyMetrics", v)}
                    className="md:col-span-1"
                    icon="📊"
                    />

                    {/* 5. Channels */}
                    <CanvasBlock
                    title="5. 채널 (Channels)"
                    subtitle="고객에게 도달하는 경로"
                    value={canvasData.channels}
                    onChange={(v) => handleChange("channels", v)}
                    className="md:col-span-1"
                    icon="📢"
                    />

                    {/* 7. Cost Structure */}
                    <CanvasBlock
                    title="7. 비용 구조 (Cost Structure)"
                    subtitle="고정비, 변동비 등 주요 비용"
                    value={canvasData.costStructure}
                    onChange={(v) => handleChange("costStructure", v)}
                    className="md:col-span-2.5 md:row-span-1"
                    icon="💸"
                    />

                    {/* 6. Revenue Streams */}
                    <CanvasBlock
                    title="6. 수익원 (Revenue Streams)"
                    subtitle="수익 모델, 가격 정책"
                    value={canvasData.revenueStreams}
                    onChange={(v) => handleChange("revenueStreams", v)}
                    className="md:col-span-2.5 md:row-span-1 bg-green-50/50 border-green-100"
                    icon="💰"
                    />
                </div>
            </div>
        </div>
      </div>

      {/* Footer CTA */}
      <div className="bg-gray-50 border-t border-gray-200 py-16 text-center">
        <h2 className="text-3xl font-bold mb-4">준비된 기획, 포트폴리오로 완성하세요</h2>
        <p className="text-gray-500 mb-8">바이브폴리오는 당신의 아이디어가 세상과 만나는 곳입니다.</p>
        <Button onClick={() => router.push('/')} variant="outline" className="h-12 px-8 rounded-full border-gray-300 hover:bg-white text-lg">
            메인으로 돌아가기
        </Button>
      </div>
    </div>
  );
}

function CanvasBlock({ 
    title, 
    subtitle, 
    value, 
    onChange, 
    className, 
    icon,
    isHighlight = false
}: { 
    title: string; 
    subtitle: string; 
    value: string; 
    onChange: (v: string) => void; 
    className?: string;
    icon: string;
    isHighlight?: boolean;
}) {
    return (
        <div className={`flex flex-col border rounded-xl p-4 transition-all duration-300 hover:shadow-md ${isHighlight ? 'border-purple-200 ring-4 ring-purple-50/50' : 'border-gray-200 hover:border-gray-400 bg-white'} ${className}`}>
            <div className="flex items-center justify-between mb-2">
                <h3 className="font-bold text-base text-gray-800 flex items-center gap-2">
                    <span className="text-lg">{icon}</span> {title}
                </h3>
            </div>
            <p className="text-xs text-gray-400 mb-3">{subtitle}</p>
            <Textarea
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className="flex-1 w-full resize-none text-sm leading-relaxed border-0 bg-transparent p-0 focus-visible:ring-0 placeholder:text-gray-300 min-h-[100px]"
                placeholder="내용이 생성됩니다..."
            />
        </div>
    );
}
