-- 1. 문의사항 테이블 (광고, 제휴 등)
CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) DEFAULT 'ad', -- ad(광고), partnership(제휴), bug(오류), other(기타)
    name VARCHAR(100), -- 문의자 이름/회사명
    email VARCHAR(255), -- 답변 받을 이메일
    phone VARCHAR(50), 
    title VARCHAR(255),
    content TEXT,
    status VARCHAR(50) DEFAULT 'pending', -- pending(대기중), in_progress(검토중), resolved(완료)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Inquiries (관리자만 조회, 누구나 생성)
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert inquiries" ON inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin select inquiries" ON inquiries FOR SELECT USING (
  -- 실제 운영 시에는 관리자 ID 체크 필요, 여기서는 일단 인증된 사용자 중 관리자만(API에서 처리) 혹은 일단 open
  auth.role() = 'authenticated' -- 임시: 로그인한 유저만 조회 가능하도록 하거나, API에서 service_role로 우회
);


-- 2. 사이트 통계 테이블 (일별 방문자수 집계용)
CREATE TABLE IF NOT EXISTS site_stats (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    visits INT DEFAULT 0, -- 방문자 수 (세션/페이지뷰)
    new_users INT DEFAULT 0, -- 신규 가입자
    new_projects INT DEFAULT 0 -- 신규 프로젝트
);

-- 통계 테이블 초기화
INSERT INTO site_stats (date, visits) VALUES (CURRENT_DATE, 1) ON CONFLICT DO NOTHING;
