-- 상세 방문 로그 테이블
-- 단순 카운팅을 넘어 유입 경로(Referrer)와 기기 정보(Device)를 분석하기 위함입니다.

CREATE TABLE IF NOT EXISTS visit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visited_at TIMESTAMPTZ DEFAULT NOW(),
    ip_address VARCHAR(50),
    user_agent TEXT,
    device_type VARCHAR(20), -- 'mobile', 'desktop', 'tablet' etc
    referrer TEXT,           -- 유입 경로 (Referer 헤더)
    path TEXT                -- 방문한 내부 페이지 경로
);

-- 통계 쿼리 성능 향상을 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_visit_logs_visited_at ON visit_logs(visited_at DESC);
CREATE INDEX IF NOT EXISTS idx_visit_logs_referrer ON visit_logs(referrer);

-- RLS 설정
ALTER TABLE visit_logs ENABLE ROW LEVEL SECURITY;

-- 기존 정책이 있다면 삭제 (에러 방지) 후 재생성
DROP POLICY IF EXISTS "Allow insert for everyone" ON visit_logs;
CREATE POLICY "Allow insert for everyone" ON visit_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow select for authenticated" ON visit_logs;
CREATE POLICY "Allow select for authenticated" ON visit_logs FOR SELECT USING (auth.role() = 'authenticated');
