-- 시스템 활동 로그 테이블
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- 행위자 (NULL이면 비로그인/시스템)
    action VARCHAR(50) NOT NULL, -- 행위 (예: LOGIN, VIEW_PAGE, CREATE_PROJECT, UPDATE_PROFILE, DELETE_POST)
    target_type VARCHAR(50), -- 대상 유형 (예: PROJECT, USER, SYSTEM)
    target_id VARCHAR(100), -- 대상 식별자
    details JSONB, -- 추가 상세 정보 (JSON)
    ip_address VARCHAR(50), -- IP 주소
    user_agent TEXT, -- 브라우저 정보
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 조회 성능을 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action ON activity_logs(action);

-- RLS 설정 (관리자만 조회 가능, 누구나 생성 가능 - API 통해)
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow insert for everyone" ON activity_logs FOR INSERT WITH CHECK (true);
-- 관리자 조회 정책은 실제 운영 시 admin role 체크 필요, 개발용으로 일단 authenticated 허용 혹은 service_role 사용
CREATE POLICY "Allow select for authenticated" ON activity_logs FOR SELECT USING (auth.role() = 'authenticated');
