-- 시스템 활동 로그 테이블
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,           -- 'CREATE', 'UPDATE', 'DELETE', 'LOGIN', etc.
  target_type TEXT NOT NULL,      -- 'PROJECT', 'BANNER', 'RECRUIT', 'USER', 'SETTINGS', etc.
  target_id TEXT,                 -- 대상 ID (선택)
  details JSONB,                  -- 변경 내용 등 상세 정보
  ip_address VARCHAR(50),
  user_id UUID REFERENCES auth.users(id), -- 수행한 관리자 ID
  user_email TEXT,                -- 편의상 이메일도 저장
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action ON activity_logs(action);

-- RLS
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- 정책: 관리자만 읽기 가능
CREATE POLICY "Allow select for admins only" ON activity_logs
  FOR SELECT USING (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- 정책: 인서트는 서버 사이드(Service Role)에서 주로 하지만, 관리자 클라이언트에서도 가능하게
CREATE POLICY "Allow insert for admins/service" ON activity_logs
  FOR INSERT WITH CHECK (true);
