-- IR(Investor Relations) 발표자료 관리 테이블

-- 1. 발표 자료 덱(Deck) 테이블 (각 팀별 자료)
CREATE TABLE IF NOT EXISTS ir_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR(100) NOT NULL, -- 팀 이름 (예: 팀 A, 팀 B...)
    title VARCHAR(255) NOT NULL,     -- 발표 주제 (예: 서비스 IR)
    description TEXT,                -- 개요
    target_audience VARCHAR(100),    -- 발표 대상 (예: VC, 심사위원)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) -- 작성자
);

-- 2. 슬라이드 테이블
CREATE TABLE IF NOT EXISTS ir_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT REFERENCES ir_decks(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL DEFAULT 0, -- 슬라이드 순서
    layout_type VARCHAR(50) DEFAULT 'basic', -- 'cover', 'basic', 'image_left', 'image_right', 'grid'
    title VARCHAR(255),
    content TEXT,        -- 본문 내용 (Markdown or Text)
    bullet_points JSONB, -- 핵심 포인트 (배열)
    image_url TEXT,      -- 슬라이드내 이미지
    speaker_notes TEXT,  -- 발표 스크립트/노트
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS 설정
ALTER TABLE ir_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ir_slides ENABLE ROW LEVEL SECURITY;

-- 정책: 관리자만 접근 가능
CREATE POLICY "Allow all for admins" ON ir_decks
    FOR ALL USING (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

CREATE POLICY "Allow all for admins" ON ir_slides
    FOR ALL USING (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

-- 초기 데이터 (5개 팀 예시)
INSERT INTO ir_decks (team_name, title, description) VALUES
('Team 1', 'Team 1 IR Presentation', '첫 번째 팀 발표 자료 초안'),
('Team 2', 'Team 2 IR Presentation', '두 번째 팀 발표 자료 초안'),
('Team 3', 'Team 3 IR Presentation', '세 번째 팀 발표 자료 초안'),
('Team 4', 'Team 4 IR Presentation', '네 번째 팀 발표 자료 초안'),
('Team 5', 'Team 5 IR Presentation', '다섯 번째 팀 발표 자료 초안');
