-- 검색 트렌드 추적을 위한 테이블 생성
CREATE TABLE IF NOT EXISTS public.search_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT UNIQUE NOT NULL,
    count INTEGER DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 검색 횟수 증가를 위한 함수
CREATE OR REPLACE FUNCTION public.increment_search_count(search_term TEXT)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.search_keywords (query, count, updated_at)
    VALUES (search_term, 1, now())
    ON CONFLICT (query)
    DO UPDATE SET 
        count = public.search_keywords.count + 1,
        updated_at = now();
END;
$$ LANGUAGE plpgsql;

-- 검색어 자동 정리를 위한 RLS 정책 (모두 읽기 가능, 익명 쓰기 가능)
ALTER TABLE public.search_keywords ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read search_keywords"
ON public.search_keywords FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow public insert/update search_keywords"
ON public.search_keywords FOR INSERT
TO anon, authenticated
WITH CHECK (true);
